SELECT * FROM UNREALIZED_GAIN_LOSS

SELECT * FROM INVESTOR
ORDER BY DoB
GO

WITH phone_amount AS(
	SELECT I.Phone, SUM(Amount) AS gain_loss
	FROM UNREALIZED_GAIN_LOSS AS GL JOIN INVESTOR AS I
	ON GL.Phone = I.Phone
	GROUP BY I.Phone)
SELECT I.Name, PA.gain_loss, I.Gender
FROM INVESTOR AS I, phone_amount AS PA
WHERE I.Phone = PA.Phone AND 2025-YEAR(I.DoB) >= 20 AND 2025-YEAR(I.DoB) <= 30
ORDER BY Gender
GO

WITH phone_amount AS(
	SELECT I.Phone, SUM(Amount) AS gain_loss
	FROM UNREALIZED_GAIN_LOSS AS GL JOIN INVESTOR AS I
	ON GL.Phone = I.Phone
	GROUP BY I.Phone)
SELECT I.Gender, CAST(AVG(PA.gain_loss) AS DECIMAL(10,2)) AS average
FROM phone_amount AS PA, INVESTOR AS I
WHERE I.Phone = PA.Phone AND 2025-YEAR(I.DoB) >= 20 AND 2025-YEAR(I.DoB) <= 30
GROUP BY I.Gender