CREATE TABLE INVESTOR (
	Phone VARCHAR(20) NOT NULL,
	Name VARCHAR(100) NOT NULL,
	Gender VARCHAR(10) NOT NULL,
	DoB DATE NOT NULL,
	AnnualIncome DECIMAL(12, 2),
	Company VARCHAR(100) NOT NULL,
	PRIMARY KEY (Phone)
);

CREATE TABLE USER_SURVEY_RESPONSES (
	Phone VARCHAR(20) NOT NULL,
    Q1Answer VARCHAR(255) NOT NULL,
    Q2Answer VARCHAR(255) NOT NULL,
    Q3Answer VARCHAR(255) NOT NULL,
    Q4Answer VARCHAR(255) NOT NULL,
    Q5Answer VARCHAR(255) NOT NULL,
	PRIMARY KEY (Phone),
	FOREIGN KEY (Phone) REFERENCES INVESTOR (Phone)
);

CREATE TABLE RISK_LEVEL_DETERMINATION (
    Q1Answer VARCHAR(255) NOT NULL,
    Q2Answer VARCHAR(255) NOT NULL,
    Q3Answer VARCHAR(255) NOT NULL,
    Q4Answer VARCHAR(255) NOT NULL,
    Q5Answer VARCHAR(255) NOT NULL,
    RiskLevel VARCHAR(20) NOT NULL CHECK (RiskLevel IN ('Conservative', 'Moderate', 'Aggressive')),
    PRIMARY KEY (Q1Answer, Q2Answer, Q3Answer, Q4Answer, Q5Answer)
);

CREATE TABLE FINANCIAL_GOAL (
	Phone VARCHAR(20) NOT NULL,
	Goal VARCHAR(255) NOT NULL,
	Timeline TEXT NOT NULL,
	Amount DECIMAL(15, 2) NOT NULL CHECK (Amount > 0),
	PRIMARY KEY (Phone, Goal),
	FOREIGN KEY (Phone) REFERENCES INVESTOR(Phone)
);

CREATE TABLE PORTFOLIO (
    Phone VARCHAR(20) NOT NULL,
    PID INT NOT NULL,
    InceptionDate DATE NOT NULL,
    AnnualizedReturn DECIMAL(5,2) DEFAULT 0,
    MarketValue DECIMAL(15,2) DEFAULT 0,
	Fee DECIMAL(15,2) DEFAULT 0,
    PRIMARY KEY (Phone, PID),
    FOREIGN KEY (Phone) REFERENCES INVESTOR(Phone)
);

CREATE TABLE INVESTED_VALUE (
    Phone VARCHAR(20) NOT NULL,
    PID INT NOT NULL,
    Date DATE NOT NULL,
    Amount DECIMAL(15,2),
    PRIMARY KEY (Phone, PID, Date),
    FOREIGN KEY (Phone, PID) REFERENCES PORTFOLIO (Phone, PID)
);

CREATE TABLE UNREALIZED_GAIN_LOSS (
    Phone VARCHAR(20) NOT NULL,
    PID INT NOT NULL,
    Date DATE NOT NULL,
    Amount DECIMAL(15,2),
    PRIMARY KEY (Phone, PID, Date),
    FOREIGN KEY (Phone, PID) REFERENCES PORTFOLIO (Phone, PID)
);

CREATE TABLE ASSET (
    ID INT NOT NULL,
    Name VARCHAR(100) NOT NULL,
    Price DECIMAL(15,2) NOT NULL,
	PRIMARY KEY (ID)
);

CREATE TABLE STOCK (
    ID INT NOT NULL,
    P_E DECIMAL(10,2),
    EPS DECIMAL(10,2),
    EBITDA DECIMAL(15,2),
	PRIMARY KEY (ID),
    FOREIGN KEY (ID) REFERENCES ASSET (ID)
);

CREATE TABLE BOND (
    ID INT NOT NULL,
    InterestRate DECIMAL(5,2),
    MaturityDate DATE NOT NULL,
	PRIMARY KEY (ID),
    FOREIGN KEY (ID) REFERENCES ASSET (ID)
);

CREATE TABLE FUND (
    ID INT NOT NULL,
    ExpenseRatio DECIMAL(5,2),
    DividendYield DECIMAL(5,2),
	PRIMARY KEY (ID),
    FOREIGN KEY (ID) REFERENCES ASSET (ID)
);

CREATE TABLE PORTFOLIO_STOCK_DETAILS (
	Phone VARCHAR(20) NOT NULL,
    ID INT NOT NULL,
    StockID INT NOT NULL,
    PID INT NOT NULL,
    StartDate DATE NOT NULL,
    AllocationRatio DECIMAL(5,2),
    PRIMARY KEY (ID),
    FOREIGN KEY (StockID) REFERENCES STOCK (ID),
	FOREIGN KEY (Phone, PID) REFERENCES PORTFOLIO
);

CREATE TABLE STOCK_POST_TRADE_COMPANY (
    StockID INT NOT NULL,
    PostTradeCO VARCHAR(255),
    PRIMARY KEY (StockID),
    FOREIGN KEY (StockID) REFERENCES STOCK (ID)
);

CREATE TABLE PORTFOLIO_BOND_DETAILS (
	Phone VARCHAR(20) NOT NULL,
    ID INT NOT NULL,
    BondID INT NOT NULL,
    PID INT NOT NULL,
    StartDate DATE NOT NULL,
    AllocationRatio DECIMAL(5,2),
    PRIMARY KEY (ID),
    FOREIGN KEY (BondID) REFERENCES BOND (ID),
	FOREIGN KEY (Phone, PID) REFERENCES PORTFOLIO
);

CREATE TABLE BOND_POST_TRADE_COMPANY (
    BondID INT NOT NULL,
    PostTradeCO VARCHAR(255),
	PRIMARY KEY (BondID),
    FOREIGN KEY (BondID) REFERENCES BOND (ID)
);

CREATE TABLE PORTFOLIO_FUND_DETAILS (
	Phone VARCHAR(20) NOT NULL,
    ID INT NOT NULL,
    FundID INT NOT NULL,
    PID INT NOT NULL,
    StartDate DATE NOT NULL,
    AllocationRatio DECIMAL(5,2),
    PRIMARY KEY (ID),
    FOREIGN KEY (FundID) REFERENCES FUND (ID),
	FOREIGN KEY (Phone, PID) REFERENCES PORTFOLIO
);

CREATE TABLE FUND_POST_TRADE_COMPANY (
    FundID INT NOT NULL,
    PostTradeCO VARCHAR(255),
	PRIMARY KEY (FundID),
    FOREIGN KEY (FundID) REFERENCES FUND (ID)
);

CREATE TABLE TRANSACTION_STOCK (
    Date DATE NOT NULL,
    ID INT NOT NULL,
    Type VARCHAR(20),
    Fee DECIMAL(10,2),
    PRIMARY KEY (Date, ID),
    FOREIGN KEY (ID) REFERENCES PORTFOLIO_STOCK_DETAILS (ID)
);

CREATE TABLE TRANSACTION_BOND (
    Date DATE NOT NULL,
    ID INT NOT NULL,
    Type VARCHAR(20),
    Fee DECIMAL(10,2),
    PRIMARY KEY (Date, ID),
    FOREIGN KEY (ID) REFERENCES PORTFOLIO_BOND_DETAILS (ID)
);

CREATE TABLE TRANSACTION_FUND (
    Date DATE NOT NULL,
    ID INT NOT NULL,
    Type VARCHAR(20),
    Fee DECIMAL(10,2),
    PRIMARY KEY (Date, ID),
    FOREIGN KEY (ID) REFERENCES PORTFOLIO_FUND_DETAILS (ID)
);

DROP TABLE IF EXISTS TRANSACTION_STOCK;
DROP TABLE IF EXISTS TRANSACTION_BOND;
DROP TABLE IF EXISTS TRANSACTION_FUND;

DROP TABLE IF EXISTS FUND_POST_TRADE_COMPANY;
DROP TABLE IF EXISTS BOND_POST_TRADE_COMPANY;
DROP TABLE IF EXISTS STOCK_POST_TRADE_COMPANY;

DROP TABLE IF EXISTS PORTFOLIO_FUND_DETAILS;
DROP TABLE IF EXISTS PORTFOLIO_BOND_DETAILS;
DROP TABLE IF EXISTS PORTFOLIO_STOCK_DETAILS;

DROP TABLE IF EXISTS FUND;
DROP TABLE IF EXISTS BOND;
DROP TABLE IF EXISTS STOCK;
DROP TABLE IF EXISTS ASSET;

DROP TABLE IF EXISTS UNREALIZED_GAIN_LOSS;
DROP TABLE IF EXISTS INVESTED_VALUE;

DROP TABLE IF EXISTS MARKET_VALUE_FEES;
DROP TABLE IF EXISTS PORTFOLIO_DETAILS;
DROP TABLE IF EXISTS PORTFOLIO;

DROP TABLE IF EXISTS FINANCIAL_GOAL;
DROP TABLE IF EXISTS RISK_LEVEL_DETERMINATION;
DROP TABLE IF EXISTS USER_SURVEY_RESPONSES;
DROP TABLE IF EXISTS INVESTOR;